---
title: "Fit"
author: "Tilde Sloth"
date: "2025-05-02"
output: html_document
---

```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/Users/tildeidunsloth/Documents/GitHub/ACM2024/Assignment_4")) 
```

```{r}
# read packages
pacman::p_load(tidyverse,
               here,
               posterior,
               cmdstanr,
               brms, tidybayes)
```


```{r}
# Specify where the model is
file <- file.path("src/stan/GCM_model.stan")

```



```{r}
# Load simulated data
sim_dat <- read.csv("data/simulated_data.csv")


```


```{r}
# load empirical data
real_d <- read.csv("data/AlienData.txt")

# make subset for subject 1 and session 1 and condition 1 
real_d <- real_d[real_d$subject == 1 & real_d$session == 1 & real_d$condition == 1, ]

# create a column "danger" with 1 for "danger" and 0 for "safe". If category is 3 or 4, it is "danger", otherwise "safe"
real_d$danger <- ifelse(real_d$category %in% c(3, 4), 1, 0)

# convert stimulus into features
real_d <- real_d %>%
  mutate(
    stim_str = gsub(".jpg", "", stimulus)
  ) %>%
  mutate(
    spots   = as.integer(substr(stim_str, 1, 1)),
    legs    = as.integer(substr(stim_str, 2, 2)),
    eyes    = as.integer(substr(stim_str, 3, 3)),
    arms_up = as.integer(substr(stim_str, 4, 4)),
    color   = as.integer(substr(stim_str, 5, 5))
  ) %>%
  select(-stim_str)

# remove rows with test = 1
real_d <- real_d[real_d$test == 0, ]

```


```{r}
# prepare data empirical
gcm_data_empirical <- list(
  trials = nrow(real_d),
  nfeatures = 5,
  danger = real_d$danger,
  response = real_d$dangerous,
  stimuli = as.matrix(real_d[, c("spots", "legs", "eyes", "arms_up", "color")]),
  w_prior_values = c(1, 1, 1, 1, 1), # uniform prior
  c_prior_values = c(0, 1) # mean and sd of the prior
)
```

```{r}
# prepare data simulated
gcm_data_simulated <- list(
  trials = nrow(sim_dat),
  nfeatures = 5,
  danger = sim_dat$danger,
  response = sim_dat$dangerous,
  stimuli = as.matrix(sim_dat[, c("spots", "legs", "eyes", "arms_up", "color")]),
  w_prior_values = c(1, 1, 1, 1, 1), # uniform prior
  c_prior_values = c(0, 1) # mean and sd of the prior
)
```


```{r}
# fit empirical data 

# Compiling the model
mod <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE))

 samples_empirical <- mod$sample(
    data = gcm_data_empirical,
    seed = 123,
    chains = 1,
    parallel_chains = 1,
    threads_per_chain = 1,
    iter_warmup = 1000,
    iter_sampling = 1000,
    refresh = 500
  )
  
  # Save model fits
  samples_empirical$save_object("empirical_fit.rds")
  
```

```{r}
# fit simulated data

samples_simulated <- mod$sample(
    data = gcm_data_simulated,
    seed = 123,
    chains = 1,
    parallel_chains = 1,
    threads_per_chain = 1,
    iter_warmup = 1000,
    iter_sampling = 1000,
    refresh = 500
  )
  
  # Save model fits
  samples_simulated$save_object("simulated_fit.rds")
```

